version: "3.8"
services:
  api:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
      build:
        context: ./frontend
      ports:
        - "3000:80"
      depends_on:
        - api